"""Posts logging — writes to both data/posts_log.md and data/posts_log.json."""

import json
from datetime import datetime, timezone

from src.config import DATA_DIR

JSON_PATH = DATA_DIR / "posts_log.json"
MD_PATH = DATA_DIR / "posts_log.md"


def load_log() -> list[dict]:
    if JSON_PATH.exists():
        return json.loads(JSON_PATH.read_text())
    return []


def save_log(entries: list[dict]):
    """Persist log to both JSON and Markdown formats."""
    # JSON
    JSON_PATH.write_text(json.dumps(entries, indent=2))

    # Markdown
    lines = [
        "# Published Posts Log\n",
        "> Auto-generated by repurpose-youtube-video. Do not edit manually.\n",
    ]

    if not entries:
        lines.append("No posts published yet.\n")
    else:
        lines.append("| # | Date | YouTube URL | Platform | Post Preview | Visual | Live URL | Status |")
        lines.append("|---|------|-------------|----------|-------------|--------|----------|--------|")
        for i, e in enumerate(entries, 1):
            preview = e.get("post_preview", "")[:60].replace("|", "\\|").replace("\n", " ")
            live = e.get("live_url", "—")
            if live and live != "—":
                live = f"[Link]({live})"
            lines.append(
                f"| {i} "
                f"| {e.get('date', '—')} "
                f"| {e.get('youtube_url', '—')} "
                f"| {e.get('platform', '—')} "
                f"| {preview} "
                f"| {e.get('visual_url', '—')} "
                f"| {live} "
                f"| {e.get('status', '—')} |"
            )

    MD_PATH.write_text("\n".join(lines) + "\n")


def log_post(youtube_url: str, platform: str, post_text: str,
             visual_url: str, live_url: str, status: str):
    """Append a single post entry to the log."""
    entries = load_log()
    entries.append({
        "date": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "youtube_url": youtube_url,
        "platform": platform,
        "post_preview": post_text[:100],
        "visual_url": visual_url or "",
        "live_url": live_url or "",
        "status": status,
    })
    save_log(entries)
