"""Turn insights JSON into a Monday-briefing markdown report.

Two modes:
- LLM mode (default): uses prompts/write_report_v1.md for a tight executive summary.
- Template mode (--no-llm): builds a deterministic markdown report from the insights directly.
  Template mode is also the automatic fallback when no LLM key is configured or the call fails.

Usage:
    python tools/write_report.py --insights .tmp/insights.json --output .tmp/report.md
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from shared.env_loader import load_env, get_optional
from shared.logger import info, warn, error
from shared.cost_tracker import check_budget, record_cost, BudgetExceededError
from shared.sandbox import validate_write_path


PROMPT_DIR = Path(__file__).parent.parent / "prompts"


def template_report(payload: dict, date_str: str) -> str:
    insights = payload.get("insights") or []
    summaries = payload.get("competitor_summaries") or {}

    lines = [f"# Competitor Digest — {date_str}", ""]

    # TL;DR: top 3 highest-score findings.
    top3 = insights[:3]
    lines.append("## TL;DR")
    if not top3:
        lines.append("- No meaningful changes this week across tracked competitors.")
    else:
        for i, f in enumerate(top3, 1):
            lines.append(f"- **{f.get('competitor')}** — {f.get('what_changed', '')[:180]} _(tag: {f.get('tag')}, score: {f.get('score')}/10)_")
    lines.append("")

    # Top findings (up to 5).
    lines.append("## Top Findings")
    if not insights:
        lines.append("_No ranked findings._")
    for f in insights[:5]:
        lines.append(f"### {f.get('rank', '?')}. {(f.get('what_changed') or 'Change')[:140]}")
        lines.append(f"**Competitor:** {f.get('competitor')} · **Tag:** {f.get('tag')} · **Score:** {f.get('score')}/10")
        lines.append(f"**What changed:** {f.get('what_changed', '')}")
        lines.append(f"**Why it matters:** {f.get('why_it_matters', '')} {f.get('rationale', '')}".strip())
        src = f.get("source") or f.get("url") or ""
        if src:
            lines.append(f"**Source:** {src}")
        lines.append("")

    lines.append("## Per-Competitor Notes")
    for name, meta in summaries.items():
        counts = meta.get("counts") or {}
        lines.append(f"### {name}")
        if meta.get("first_run"):
            lines.append("- First run: baseline captured, no prior snapshot to diff against.")
        elif counts.get("total", 0) == 0:
            lines.append("- No meaningful changes this week.")
        else:
            lines.append(f"- Added: {counts.get('added', 0)} · Removed: {counts.get('removed', 0)} · Modified: {counts.get('modified', 0)}")
            top_for_comp = [f for f in insights if f.get("competitor") == name][:3]
            for f in top_for_comp:
                lines.append(f"  - _{f.get('tag')}_: {(f.get('what_changed') or '')[:140]}")
        lines.append("")

    lines.append("## Watchlist")
    lines.append("- Monitor next week for follow-ups on pricing/launch signals flagged above.")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Angelina-OS Research Agent — weekly cycle*")
    return "\n".join(lines)


def llm_report(payload: dict, date_str: str, business_context: str, run_id: str) -> str | None:
    from openai import OpenAI
    euri = get_optional("EURI_API_KEY")
    orkey = get_optional("OPENROUTER_API_KEY")
    if euri:
        client = OpenAI(base_url="https://api.euron.one/api/v1/euri", api_key=euri)
        model, provider = "gpt-4o-mini", "euri"
    elif orkey:
        client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=orkey)
        model, provider = "openai/gpt-4o-mini", "openrouter"
    else:
        return None

    est_cost = 0.02
    try:
        check_budget(estimated_cost=est_cost, run_id=run_id)
    except BudgetExceededError as e:
        warn(f"skip LLM report — budget: {e}")
        return None

    tpl = (PROMPT_DIR / "write_report_v1.md").read_text()
    ranked_findings = payload.get("insights", [])[:5]
    competitor_summaries = payload.get("competitor_summaries") or {}

    prompt = (tpl
              .replace("{business_context}", business_context)
              .replace("{date}", date_str)
              .replace("{ranked_findings_json}", json.dumps(ranked_findings, ensure_ascii=False))
              .replace("{competitors_summary}", json.dumps(competitor_summaries, ensure_ascii=False)))

    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=1800,
        )
        record_cost(f"write_report:{provider}", est_cost, run_id=run_id)
        return (resp.choices[0].message.content or "").strip()
    except Exception as e:
        warn(f"LLM report failed: {e} — falling back to template")
        return None


def main():
    parser = argparse.ArgumentParser(description="Write weekly research report")
    parser.add_argument("--insights", default=".tmp/insights.json")
    parser.add_argument("--output", default=".tmp/report.md")
    parser.add_argument("--business-context", default="AI automation platforms")
    parser.add_argument("--no-llm", action="store_true")
    parser.add_argument("--run-id", default=None)
    args = parser.parse_args()

    load_env()
    project_root = Path(__file__).parent.parent
    insights_path = project_root / args.insights
    if not insights_path.exists():
        error(f"insights file missing: {insights_path}")
        sys.exit(1)

    payload = json.loads(insights_path.read_text())
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    md = None
    if not args.no_llm:
        md = llm_report(payload, date_str, args.business_context, args.run_id or "adhoc")
    if not md:
        md = template_report(payload, date_str)
        info("report generated via template fallback")
    else:
        info("report generated via LLM")

    output_path = validate_write_path(str(project_root / args.output))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(md)
    print(json.dumps({"status": "success", "output_path": str(output_path), "length": len(md)}))


if __name__ == "__main__":
    main()
