"""
Scaffold a guardrail pipeline for a new project.

Usage:
    python scaffold.py --domain university --roles student,admin,viewer --tables students,courses,transactions --output ./guardrails
"""

import argparse
import os

POLICY_TEMPLATE = '''"""
Policy Layer Guardrail — Role-based access control, rate limiting, data scope enforcement.
Generated by guardrail-pipeline skill.
"""

import time
import re
from dataclasses import dataclass, field


@dataclass
class PolicyResult:
    allowed: bool
    reason: str
    policy_name: str
    details: dict = field(default_factory=dict)


ROLE_PERMISSIONS = {{
{role_permissions}
}}

SCHEMA_KEYWORDS = [
    "schema", "column", "columns", "structure", "table structure",
    "describe table", "table definition", "field", "fields",
    "data type", "datatype", "primary key", "foreign key",
]


class PolicyGuardrail:

    def __init__(self):
        self._request_timestamps: dict[str, list[float]] = {{}}
        self.rate_limit_window = {rate_window}
        self.rate_limit_max = {rate_max}

    def check_all(self, user_input: str, role: str = "{default_role}", session_id: str = "") -> list[PolicyResult]:
        results = []
        results.append(self.check_role_permission(role))
        results.append(self.check_rate_limit(session_id))
        results.append(self.check_schema_access(user_input, role))
        results.append(self.check_operation_policy(user_input))
        return results

    def is_blocked(self, results: list[PolicyResult]) -> bool:
        return any(not r.allowed for r in results)

    def check_role_permission(self, role: str) -> PolicyResult:
        if role not in ROLE_PERMISSIONS:
            return PolicyResult(False, f"Unknown role '{{role}}'. Access denied.", "role_permission", {{"role": role}})
        perms = ROLE_PERMISSIONS[role]
        return PolicyResult(True, f"Role '{{role}}' recognized. {{perms['description']}}", "role_permission", {{"role": role}})

    def check_rate_limit(self, session_id: str) -> PolicyResult:
        now = time.time()
        if session_id not in self._request_timestamps:
            self._request_timestamps[session_id] = []
        self._request_timestamps[session_id] = [
            t for t in self._request_timestamps[session_id] if now - t < self.rate_limit_window
        ]
        if len(self._request_timestamps[session_id]) >= self.rate_limit_max:
            return PolicyResult(False, f"Rate limit exceeded: {{self.rate_limit_max}} requests per {{self.rate_limit_window}}s.", "rate_limit")
        self._request_timestamps[session_id].append(now)
        return PolicyResult(True, "Within rate limit.", "rate_limit")

    def check_schema_access(self, user_input: str, role: str) -> PolicyResult:
        perms = ROLE_PERMISSIONS.get(role, {{}})
        if perms.get("can_view_schema", False):
            return PolicyResult(True, "Schema access permitted.", "schema_access")
        input_lower = user_input.lower()
        for kw in SCHEMA_KEYWORDS:
            if kw in input_lower:
                return PolicyResult(False, f"Schema access denied for role '{{role}}'.", "schema_access", {{"matched": kw}})
        return PolicyResult(True, "No schema access attempted.", "schema_access")

    def check_operation_policy(self, user_input: str) -> PolicyResult:
        blocked_ops = {blocked_ops}
        input_upper = user_input.upper()
        for op in blocked_ops:
            if re.search(rf"\\b{{op}}\\b", input_upper):
                return PolicyResult(False, f"Operation '{{op}}' is blocked.", "operation_policy", {{"blocked": op}})
        return PolicyResult(True, "No blocked operations detected.", "operation_policy")
'''

INPUT_GUARD_TEMPLATE = '''"""
Input Layer Guardrail — SQL injection, prompt injection, PII detection.
Generated by guardrail-pipeline skill.
"""

import re
from dataclasses import dataclass, field


@dataclass
class InputCheckResult:
    passed: bool
    reason: str
    check_name: str
    sanitized_input: str | None = None
    details: dict = field(default_factory=dict)


SQL_INJECTION_PATTERNS = [
    r"(?i)\\b(union\\s+select)\\b",
    r"(?i)(\\b(or|and)\\b\\s+[\\\'\\"]?\\d+[\\\'\\"]?\\s*=\\s*[\\\'\\"]?\\d+)",
    r"(?i)(;\\s*(drop|alter|truncate|delete|update|insert)\\b)",
    r"(?i)(--\\s|/\\*|\\*/)",
    r"(?i)\\b(exec|execute|xp_|sp_)\\b",
    r"(?i)(sleep\\s*\\(\\s*\\d+\\s*\\))",
    r"(?i)(benchmark\\s*\\()",
    r"(?i)(load_file|into\\s+outfile|into\\s+dumpfile)",
]

PROMPT_INJECTION_PATTERNS = [
    r"(?i)(ignore\\s+(all\\s+)?(previous|above|prior)\\s+(instructions?|prompts?|rules?))",
    r"(?i)(forget\\s+(all\\s+)?(your\\s+)?(instructions?|rules?|training))",
    r"(?i)(override\\s+(your\\s+)?(instructions?|safety|rules?))",
    r"(?i)(jailbreak|bypass\\s+(the\\s+)?(filter|guardrail|safety))",
    r"(?i)(pretend\\s+(you\\s+)?(are|to\\s+be)\\s+)",
    r"(?i)(reveal\\s+(your\\s+)?(system\\s+)?(prompt|instructions?))",
]

PII_PATTERNS = {{
    "ssn": r"\\b\\d{{3}}-\\d{{2}}-\\d{{4}}\\b",
    "credit_card": r"\\b(?:\\d{{4}}[-\\s]?){{3}}\\d{{4}}\\b",
    "phone": r"\\b(?:\\+1[-.\\ s]?)?\\(?\\d{{3}}\\)?[-.\\s]?\\d{{3}}[-.\\s]?\\d{{4}}\\b",
}}


class InputGuardrail:

    def check_all(self, user_input: str, role: str = "{default_role}") -> list[InputCheckResult]:
        results = []
        results.append(self.check_length(user_input))
        results.append(self.check_empty(user_input))
        results.append(self.check_sql_injection(user_input))
        results.append(self.check_prompt_injection(user_input))
        results.append(self.check_pii(user_input))
        return results

    def is_blocked(self, results: list[InputCheckResult]) -> bool:
        return any(not r.passed for r in results)

    def get_sanitized(self, user_input: str) -> str:
        sanitized = user_input.strip()
        sanitized = re.sub(r"[;]", "", sanitized)
        sanitized = re.sub(r"--.*$", "", sanitized, flags=re.MULTILINE)
        for name, pattern in PII_PATTERNS.items():
            sanitized = re.sub(pattern, f"[REDACTED_{{name.upper()}}]", sanitized)
        return sanitized

    def check_length(self, user_input: str) -> InputCheckResult:
        max_len = {max_input_length}
        if len(user_input) > max_len:
            return InputCheckResult(False, f"Input exceeds {{max_len}} chars.", "input_length")
        return InputCheckResult(True, "Input length OK.", "input_length")

    def check_empty(self, user_input: str) -> InputCheckResult:
        if not user_input or not user_input.strip():
            return InputCheckResult(False, "Input is empty.", "empty_input")
        return InputCheckResult(True, "Input is not empty.", "empty_input")

    def check_sql_injection(self, user_input: str) -> InputCheckResult:
        for pattern in SQL_INJECTION_PATTERNS:
            match = re.search(pattern, user_input)
            if match:
                return InputCheckResult(False, f"SQL injection detected: '{{match.group()}}'", "sql_injection")
        return InputCheckResult(True, "No SQL injection detected.", "sql_injection")

    def check_prompt_injection(self, user_input: str) -> InputCheckResult:
        for pattern in PROMPT_INJECTION_PATTERNS:
            match = re.search(pattern, user_input)
            if match:
                return InputCheckResult(False, f"Prompt injection detected: '{{match.group()}}'", "prompt_injection")
        return InputCheckResult(True, "No prompt injection detected.", "prompt_injection")

    def check_pii(self, user_input: str) -> InputCheckResult:
        found = {{}}
        for name, pattern in PII_PATTERNS.items():
            if re.findall(pattern, user_input):
                found[name] = True
        if found:
            return InputCheckResult(True, f"PII detected and will be redacted: {{found}}", "pii_detection",
                                    sanitized_input=self.get_sanitized(user_input))
        return InputCheckResult(True, "No PII detected.", "pii_detection")
'''

MONITORING_TEMPLATE = '''"""
Monitoring Layer Guardrail — Full pipeline audit logging.
Generated by guardrail-pipeline skill.
"""

import json
from datetime import datetime, timezone
from dataclasses import dataclass, field


@dataclass
class MonitoringRecord:
    session_id: str
    user_input: str
    sanitized_input: str | None
    guardrail_layer: str
    guardrail_name: str
    action: str  # passed, blocked, flagged, filtered
    details: dict = field(default_factory=dict)
    tool_called: str | None = None
    tool_allowed: bool | None = None
    llm_raw_output: str | None = None
    llm_final_output: str | None = None
    hallucination_flag: bool = False
    blocked: bool = False
    execution_time_ms: float | None = None


class MonitoringGuardrail:

    def __init__(self):
        self._buffer: list[dict] = []

    def log(self, record: MonitoringRecord):
        entry = {{
            "session_id": record.session_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "user_input": record.user_input,
            "sanitized_input": record.sanitized_input,
            "guardrail_layer": record.guardrail_layer,
            "guardrail_name": record.guardrail_name,
            "action": record.action,
            "details": json.dumps(record.details) if record.details else None,
            "tool_called": record.tool_called,
            "tool_allowed": record.tool_allowed,
            "llm_raw_output": record.llm_raw_output,
            "llm_final_output": record.llm_final_output,
            "hallucination_flag": record.hallucination_flag,
            "blocked": record.blocked,
            "execution_time_ms": record.execution_time_ms,
        }}
        self._buffer.append(entry)

    def flush(self, db_client, table_name="guardrail_logs"):
        """Flush logs to database. Pass your DB client."""
        if not self._buffer:
            return
        try:
            for entry in self._buffer:
                db_client.table(table_name).insert(entry).execute()
            self._buffer.clear()
        except Exception as e:
            print(f"[MonitoringGuardrail] Failed to flush: {{e}}")

    def log_layer(self, session_id: str, user_input: str, layer: str, name: str, passed: bool, details: dict = None):
        self.log(MonitoringRecord(
            session_id=session_id, user_input=user_input, sanitized_input=None,
            guardrail_layer=layer, guardrail_name=name,
            action="passed" if passed else "blocked",
            details=details or {{}}, blocked=not passed,
        ))
'''


def generate_role_permissions(roles: list[str], tables: list[str]) -> str:
    """Generate ROLE_PERMISSIONS dict string for the given roles and tables."""
    lines = []
    for i, role in enumerate(roles):
        is_admin = role.lower() in ("admin", "super_admin", "superadmin")
        is_viewer = role.lower() in ("viewer", "readonly", "read_only")
        table_set = repr(set(tables + (["guardrail_logs"] if is_admin else [])))
        all_tools = ", ".join(f'"{t}"' for t in ["query_" + t for t in tables])

        if is_admin:
            allowed_tools = f'{{{all_tools}, "get_table_schema", "run_custom_query"}}'
            blocked_tools = "set()"
            can_schema = "True"
            can_email = "True"
            can_financial = "True"
            desc = f"{role}: full access to all data, schema, custom queries."
        elif is_viewer:
            limited_tables = tables[:2] if len(tables) > 2 else tables
            allowed_tools = "{" + ", ".join(f'"query_{t}"' for t in limited_tables) + "}"
            blocked_tools = '{"get_table_schema", "run_custom_query"}'
            can_schema = "False"
            can_email = "False"
            can_financial = "False"
            desc = f"{role}: read-only limited access."
        else:
            allowed_tools = "{" + all_tools + "}"
            blocked_tools = '{"get_table_schema", "run_custom_query"}'
            can_schema = "False"
            can_email = "False"
            can_financial = "False"
            desc = f"{role}: standard access to allowed tables."

        lines.append(f'    "{role}": {{')
        lines.append(f'        "allowed_tables": {table_set},')
        lines.append(f'        "allowed_ops": {{"SELECT"}},')
        lines.append(f'        "allowed_tools": {allowed_tools},')
        lines.append(f'        "blocked_tools": {blocked_tools},')
        lines.append(f'        "can_view_schema": {can_schema},')
        lines.append(f'        "can_view_emails": {can_email},')
        lines.append(f'        "can_view_financial": {can_financial},')
        lines.append(f'        "description": "{desc}",')
        lines.append(f'    }},')

    return "\n".join(lines)


def scaffold(domain: str, roles: list[str], tables: list[str], output_dir: str,
             max_input_length: int = 2000, rate_window: int = 60, rate_max: int = 30):
    """Generate guardrail files for the given configuration."""
    os.makedirs(os.path.join(output_dir, "guardrails"), exist_ok=True)

    default_role = roles[0]
    blocked_ops = repr({"DROP", "TRUNCATE", "ALTER", "CREATE", "DELETE", "UPDATE", "INSERT"})
    role_perms = generate_role_permissions(roles, tables)

    # Write policy.py
    policy = POLICY_TEMPLATE.format(
        role_permissions=role_perms,
        rate_window=rate_window,
        rate_max=rate_max,
        default_role=default_role,
        blocked_ops=blocked_ops,
    )
    with open(os.path.join(output_dir, "guardrails", "policy.py"), "w") as f:
        f.write(policy)

    # Write input_guard.py
    input_guard = INPUT_GUARD_TEMPLATE.format(
        default_role=default_role,
        max_input_length=max_input_length,
    )
    with open(os.path.join(output_dir, "guardrails", "input_guard.py"), "w") as f:
        f.write(input_guard)

    # Write monitoring.py
    with open(os.path.join(output_dir, "guardrails", "monitoring.py"), "w") as f:
        f.write(MONITORING_TEMPLATE)

    # Write __init__.py
    with open(os.path.join(output_dir, "guardrails", "__init__.py"), "w") as f:
        f.write("")

    print(f"Scaffolded guardrail pipeline in {output_dir}/guardrails/")
    print(f"  Domain: {domain}")
    print(f"  Roles: {roles}")
    print(f"  Tables: {tables}")
    print(f"  Files: policy.py, input_guard.py, monitoring.py, __init__.py")
    print(f"\n  TODO: Add instruction.py, execution.py, output_guard.py")
    print(f"  (customize topic keywords, tool access, output filters for your domain)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scaffold a guardrail pipeline")
    parser.add_argument("--domain", required=True, help="Application domain")
    parser.add_argument("--roles", required=True, help="Comma-separated roles")
    parser.add_argument("--tables", required=True, help="Comma-separated table names")
    parser.add_argument("--output", default=".", help="Output directory")
    parser.add_argument("--max-input-length", type=int, default=2000)
    parser.add_argument("--rate-window", type=int, default=60)
    parser.add_argument("--rate-max", type=int, default=30)

    args = parser.parse_args()
    scaffold(
        domain=args.domain,
        roles=args.roles.split(","),
        tables=args.tables.split(","),
        output_dir=args.output,
        max_input_length=args.max_input_length,
        rate_window=args.rate_window,
        rate_max=args.rate_max,
    )
